### ISSUE TITLE
readCSVObjects() object can't be cast

### ISSUE THREAD

**Issue by atinybeardedman** [vslinko/deno-csv#4]
When called the readCSVObjects() method the resulting object creating cannot be cast to a custom interface and therefore no type safety can be maintained.

Example:
```
for await (const obj of readCSVObjects()){
  const thing = obj as Thing; // this causes an error
}
```

The method produces an object of type { [key:string]: string } rather than a type of any. I understand the use of an any type would suggest that the csv object might contain values that aren't strings, but as such no interface can be cast with the resulting object which I think is more apt to error.

**Comment by vslinko** [comment]
Hi @atinybeardedman!

I could transfer ownership of result type to library users and change function definition to `readCSVObjects<T = { [key: string]: string }>(): AsyncIterable<T>`. It could make code simpler but it gives no real type safety because of `any` under the hood.

If you want type safety I would suggest to use type guards that could cast generic object to specific type. For example:

```ts
function isThing(obj: {[key: string]: string} | Thing): obj is Thing {
  return typeof obj.a === 'string';
}
```

Are type guards fits to your use case?

**Comment by vslinko** [comment]
Closed due inactivity.
